- name: First Play 
  hosts: ubuntu 
  gather_facts: no

  tasks:
    - name: Ping the ubuntu ansible node
      ping:

- name: Second Play 
  hosts: centos 
  gather_facts: no

  tasks:
    - name: Ping the centos ansible node
      ping:
